CREATE TABLE Recipes (
    Id SERIAL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL
);

CREATE TABLE RecipeIngredients (
    Id SERIAL PRIMARY KEY,
    RecipeId INTEGER NOT NULL REFERENCES Recipes(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE RecipeInstructions (
    Id SERIAL PRIMARY KEY,
    RecipeId INTEGER NOT NULL REFERENCES Recipes(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE RecipeNotes (
    Id SERIAL PRIMARY KEY,
    RecipeId INTEGER NOT NULL REFERENCES Recipes(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE RecipeNutrition (
    Id SERIAL PRIMARY KEY,
    RecipeId INTEGER NOT NULL REFERENCES Recipes(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE RecipeMacros (
    Id SERIAL PRIMARY KEY,
    RecipeId INTEGER NOT NULL REFERENCES Recipes(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
); 