CREATE TABLE Blogs (
    Id SERIAL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL
);

CREATE TABLE BlogIngredients (
    Id SERIAL PRIMARY KEY,
    BlogId INTEGER NOT NULL REFERENCES Blogs(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE BlogInstructions (
    Id SERIAL PRIMARY KEY,
    BlogId INTEGER NOT NULL REFERENCES Blogs(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE BlogNotes (
    Id SERIAL PRIMARY KEY,
    BlogId INTEGER NOT NULL REFERENCES Blogs(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE BlogNutrition (
    Id SERIAL PRIMARY KEY,
    BlogId INTEGER NOT NULL REFERENCES Blogs(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
);

CREATE TABLE BlogMacros (
    Id SERIAL PRIMARY KEY,
    BlogId INTEGER NOT NULL REFERENCES Blogs(Id) ON DELETE CASCADE,
    Value TEXT NOT NULL
); 